
# Teste de requisição GET - Listar Noticias
GET http://localhost:5000/noticias/lista HTTP/1.1

###

# Teste de requisição GET - Listar Noticias
GET http://localhost:5000/noticias/paginadas?page=1&limit=10 HTTP/1.1

###

# Teste de requisição GET - Buscar Noticia por Id
GET http://localhost:5000/noticias/1bce90cb-851c-4814-87f9-a4f63aceff88 HTTP/1.1

###

# Teste de requisição POST
POST http://localhost:5000/noticias HTTP/1.1
Content-Type: application/json

{
  "titulo": "Impacto da Inteligência Artificial nas Indústrias do Futuro: Como as Tecnologias Emergentes Estão Redefinindo o Mercado de Trabalho e a Produção Global. O avanço da inteligência artificial (IA) está transformando rapidamente diversos setores, desde a manufatura até a saúde e a educação. Empresas estão adotando IA para otimizar processos, melhorar a eficiência e criar novas oportunidades de negócio. Com a automação em ascensão, muitas funções humanas estão sendo substituídas por sistemas inteligentes, mas também estão surgindo novas profissões e áreas de atuação. O desafio será equilibrar inovação tecnológica com os impactos sociais e econômicos dessa transformação disruptiva.",
  "descricao": "A integração da inteligência artificial (IA) nas indústrias visa aumentar a produtividade e reduzir custos. A automação de processos repetitivos e o uso de algoritmos para prever tendências permitem uma produção mais eficiente e menos propensa a erros. Porém, a adoção massiva da IA também levanta questões sobre a substituição de empregos, criando uma necessidade urgente de requalificação da força de trabalho."
}

###

# Teste de requisição PUT
PUT http://localhost:5000/noticias/1bce90cb-851c-4814-87f9-a4f63aceff88 HTTP/1.1
Content-Type: application/json

{
  "titulo": "Notícia Editada",
  "descricao": "Detalhes sobre a notícia editada."
}

###

# Teste de requisição DELETE - Deletar Noticia
DELETE http://localhost:5000/noticias/1bce90cb-851c-4814-87f9-a4f63aceff88 HTTP/1.1
